[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps =
    https://github.com/compilerNayan/c_b_device_connectivity.git
    https://github.com/compilerNayan/d_b_device_identity.git
build_unflags = -fno-exceptions
build_flags = -fexceptions
